export const LoginPageStyle = {
	container: {
		display: 'flex',
		minHeight: '100vh',
		alignItems: 'center',
		justifyContent: 'center',
		background: 'var(--background)',
		padding: '1rem',
	},
	wrapper: {
		width: '100%',
		maxWidth: '28rem',
	},
	header: {
		textAlign: 'center' as const,
		marginBottom: '1.5rem',
	},
	title: {
		fontSize: '1.875rem',
		fontWeight: 'bold',
		color: 'var(--foreground)',
		margin: 0,
	},
	subtitle: {
		marginTop: '0.5rem',
		fontSize: '0.875rem',
		color: 'var(--foreground)',
		opacity: 0.6,
	},
	form: {
		display: 'flex',
		flexDirection: 'column' as const,
		gap: '1rem',
		borderRadius: '0.5rem',
		border: '1px solid color-mix(in srgb, var(--foreground) 10%, transparent)',
		background: 'var(--background)',
		padding: '1.5rem',
		boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
	},
	field: {
		display: 'flex',
		flexDirection: 'column' as const,
		gap: '0.5rem',
	},
	label: {
		display: 'block',
		fontSize: '0.875rem',
		fontWeight: 500,
		color: 'var(--foreground)',
	},
	input: {
		width: '100%',
		borderRadius: '0.375rem',
		border: '1px solid color-mix(in srgb, var(--foreground) 20%, transparent)',
		background: 'var(--background)',
		padding: '0.5rem 0.75rem',
		color: 'var(--foreground)',
		fontSize: '1rem',
		transition: 'all 0.2s',
	},
	button: {
		width: '100%',
		borderRadius: '0.375rem',
		background: 'var(--foreground)',
		padding: '0.5rem 1rem',
		fontWeight: 500,
		color: 'var(--background)',
		border: 'none',
		cursor: 'pointer',
		transition: 'opacity 0.2s',
		fontSize: '1rem',
	},
	footer: {
		textAlign: 'center' as const,
		fontSize: '0.875rem',
		color: 'var(--foreground)',
		opacity: 0.6,
		marginTop: '1rem',
	},
	link: {
		fontWeight: 500,
		color: 'var(--foreground)',
		opacity: 1,
		textDecoration: 'none',
	},
}
