import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by @TobsBP",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul style={{ display: 'flex', listStyle: 'none', padding: 0, gap: '1rem' }}>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">Sobre</Link></li>
            <li><Link href="/products">Produtos</Link></li>
          </ul>
        </nav>
        <hr />
        <main>{children}</main>
      </body>
    </html>
  );
}
