import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/src/components/layout/NavBar/Navbar'

export const metadata: Metadata = {
	title: 'E-Commerce',
	description: 'Generated by @TobsBP',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="bg-gray-100 text-gray-900">
				<Navbar />
				<main className="p-6">{children}</main>
			</body>
		</html>	)
}
