import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/NavBar'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
	title: 'E-Commerce',
	description: 'Generated by @TobsBP',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const token = (await cookies()).get('token')?.value

	return (
		<html lang="pt">
			<body>
				{token && <Navbar />}
				{children}
			</body>
		</html>
	)
}
